=== Elbareth/WhatsNewInJavaXXX/XMLParser/new.dtd
<!--We create main xml element zero or more-->
<!ELEMENT root (deer| whatever| fine)*>
<!--Then we declare the first node in xml one or more-->
<!ELEMENT deer (recent| highway| pipe)+>
<!--We create node with required value-->
<!ELEMENT recent (#PCDATA)>
<!ATTLIST recent place CDATA #REQUIRED>
<!-- ? - zero or one entry -->
<!ELEMENT highway (gas, low, zoo)>
<!ELEMENT gas (#PCDATA)>
<!ELEMENT low (#PCDATA)>
<!ELEMENT zoo (#PCDATA)>
<!ELEMENT pipe (#PCDATA)>
<!--In the next step, we declare the list of attribute of the second node-->
<!--IMPLIED means optional-->
<!ELEMENT whatever (#PCDATA)>
<!ATTLIST whatever life CDATA #IMPLIED>
<!ELEMENT fine (#PCDATA)>

=== Elbareth/WhatsNewInJavaXXX/XMLParser/new.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--We import our dtd file to check if our xml is correct-->
<!DOCTYPE root SYSTEM "new.dtd">
<root>
    <deer>
        <recent place="there">-1457040302.699809</recent>
        <highway>
            <gas>carried</gas>
            <low>1959598633</low>
            <zoo>-431840101</zoo>
        </highway>
        <pipe>student</pipe>
    </deer>
    <deer>
        <recent place="there">-1457040302.699809</recent>
        <highway>
            <gas>carried</gas>
            <low>1959598633</low>
            <zoo>-431840101</zoo>
        </highway>
        <pipe>student</pipe>
    </deer>
    <whatever life="say">sweet</whatever>
    <fine>ring</fine>
</root>
